### ISSUE TITLE
Communication failed. 

### ISSUE THREAD

**Issue by JieZhou0805** [mccorby/PhotoLabeller#6]
I have read the issues "The client can't communicate with the server" and have some questions. I met the same situation. I have already configurated the server IP. The server can be visited by the phone, but the client can't visit it. I saw someone mention the model.zip before. But I don't know where to place it. If anyone can give me some help, I will be very grateful.

**Comment by VatsaPatel** [comment]
First read the readme of server and edit your config in local.properties. and paste model.zip in there

Then change config on client to your server's ip address

**Comment by JieZhou0805** [comment]
The config on client have changed to my server's ip address.  The path of sdk have configured in local.properties. Should I paste model.zip into model directory in server?
In additon, I visited http://localhost:9997/service/federatedservice/currentRound and received followed infomation: {"modelVersion":"round_20190404_145138","startDate":1554360698807,"endDate":1554447098807,"minUpdates":1000}. I counted the time difference between the start time and the end time. This time difference should be my training time. But this time does not match the time I run the app.

**Comment by JieZhou0805** [comment]
About model.zip, will it create a new one after training? If so, then where will it be saved? Is in the same directory of Json file?

**Comment by VatsaPatel** [comment]
Model will be saved in the directory that you provided in parameters.

**Comment by JieZhou0805** [comment]
Is this directory http://ServerIp:port/service/federatedservice/ ? If not, could you please tell me where to set parameters? It's a bit difficult for me to find it out.

**Comment by VatsaPatel** [comment]
> The training process expects three arguments:

train string to trigger the process
A valid directory to save the resulting model
The third optional argument can be web to start the UI monitor provided by DL4J

>

**Comment by JieZhou0805** [comment]
When I run main.kt, the program will report an error: 
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0 at com.mccorby.photolabeller.ml.MainKt.main(Main.kt:42)
Process finished with exit code 1

How could I solve this problem? Thank you very much for your answer.

**Comment by AlexNmSED** [comment]
> When I run main.kt, the program will report an error:
> Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0 at com.mccorby.photolabeller.ml.MainKt.main(Main.kt:42)
> Process finished with exit code 1
> 
> How could I solve this problem? Thank you very much for your answer.

I met the same situation. Have you solved it yet?

**Comment by Allanwby0516** [comment]
Hi @JieZhou0805 @JieZhou0805 
I solved this problem
If you use IntelliJ or Android Studio, You should right-click Main.kt -> Edit 'MainKt' -> 
Add `train /directory web` in  Program arguments column, and you can open the DL4J UI and training!
Annotation: `/directory` is a valid directory to save the resulting model.

**Comment by Allanwby0516** [comment]
Hi @AlexNmSED @JieZhou0805 
I solved this problem
If you use IntelliJ or Android Studio, You should right-click Main.kt -> Edit 'MainKt' -> 
Add `train /directory web` in  Program arguments column, and you can open the DL4J UI and training!
Annotation: `/directory` is a valid directory to save the resulting model.
